name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Lint
        run: ruff check .
      - name: Tests
        env:
          PYTHONPATH: src
        run: pytest -q
      - name: Training smoke & upload artifacts
        env:
          PYTHONPATH: src
        run: |
          python -m mlops_diabetes.train_v0_1 --artifacts-dir artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: v0.1-artifacts
          path: artifacts/
