name: Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io

jobs:
  build-push-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Normalize image name (lowercase)
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Train to produce metrics
        env:
          PYTHONPATH: src
        run: |
          python -m mlops_diabetes.train_v0_1 --artifacts-dir artifacts
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest
      - name: Smoke test container
        run: |
          docker run -d -p 8000:8000 --name api ghcr.io/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          sleep 5
          curl -f http://localhost:8000/health
          docker logs api || true
          docker rm -f api
      - name: Extract metrics
        run: |
          echo "## Metrics" > RELEASE_BODY.md
          if [ -f artifacts/metrics_v0_1.json ]; then
            echo '\n### v0.1' >> RELEASE_BODY.md
            cat artifacts/metrics_v0_1.json >> RELEASE_BODY.md
          fi
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: RELEASE_BODY.md
          name: ${{ github.ref_name }}
